title: Hello, world! I'm Royal Bhati
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I try to explain Machine Learning topics in a simple way.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Royal Bhati # add your name
author-img: royal.jpg # add your photo
about-author: I am a python developer focusing on Machine Learning and Deep learning. Always hungry to keep learning. # add description
social-twitter: royal_bhati
social-facebook: # add your Facebook handle
social-github: royalbhati # add your Github handle
social-linkedin:royal-bhati-bb1052170 # add your Linkedin handle
social-email: royal240596@gmail.com

# Disqus
discus-identifier: royalb # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
